<?php

/**
 * This is the model base class for the table "tbl_reports".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Reports".
 *
 * Columns in table "tbl_reports" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $from
 * @property string $type
 * @property string $content
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 * @property integer $post_id
 * @property integer $user_id
 *
 */
abstract class BaseReports extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_reports';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Reports|Reports', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('from, created_at, updated_at, status, post_id, user_id', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>255),
			array('content', 'safe'),
			array('from, type, content, created_at, updated_at, status, post_id, user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, from, type, content, created_at, updated_at, status, post_id, user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'from' => Yii::t('app', 'From'),
			'type' => Yii::t('app', 'Type'),
			'content' => Yii::t('app', 'Content'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'post_id' => Yii::t('app', 'Post'),
			'user_id' => Yii::t('app', 'User'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('from', $this->from);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('status', $this->status);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('user_id', $this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}