<?php

/**
 * This is the model base class for the table "tbl_cat_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CatUser".
 *
 * Columns in table "tbl_cat_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $cat_id
 * @property integer $user_id
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 *
 */
abstract class BaseCatUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_cat_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CatUser|CatUsers', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, cat_id, user_id, status, created_at, updated_at', 'numerical', 'integerOnly'=>true),
			array('cat_id, user_id, status, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, cat_id, user_id, status, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'cat_id' => Yii::t('app', 'Cat'),
			'user_id' => Yii::t('app', 'User'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('cat_id', $this->cat_id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}