<?php

/**
 * This is the model base class for the table "tbl_user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "tbl_user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $facebook_id
 * @property string $facebook_access_token
 * @property string $username
 * @property string $password
 * @property string $photo
 * @property integer $gender
 * @property integer $age
 * @property string $description
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $access_token
 * @property integer $is_online
 * @property string $device_id
 * @property integer $status
 *
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'facebook_id';
	}

	public function rules() {
		return array(
			array('gender, age, created_at, updated_at, is_online, status', 'numerical', 'integerOnly'=>true),
			array('facebook_id', 'length', 'max'=>225),
			array('username, password, photo, access_token, device_id', 'length', 'max'=>255),
			array('facebook_access_token, description', 'safe'),
			array('facebook_id, facebook_access_token, username, password, photo, gender, age, description, created_at, updated_at, access_token, is_online, device_id, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, facebook_id, facebook_access_token, username, password, photo, gender, age, description, created_at, updated_at, access_token, is_online, device_id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'facebook_id' => Yii::t('app', 'Facebook'),
			'facebook_access_token' => Yii::t('app', 'Facebook Access Token'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'photo' => Yii::t('app', 'Photo'),
			'gender' => Yii::t('app', 'Gender'),
			'age' => Yii::t('app', 'Age'),
			'description' => Yii::t('app', 'Description'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'access_token' => Yii::t('app', 'Access Token'),
			'is_online' => Yii::t('app', 'Is Online'),
			'device_id' => Yii::t('app', 'Device'),
			'status' => Yii::t('app', 'Status'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('facebook_id', $this->facebook_id, true);
		$criteria->compare('facebook_access_token', $this->facebook_access_token, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('photo', $this->photo, true);
		$criteria->compare('gender', $this->gender);
		$criteria->compare('age', $this->age);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('access_token', $this->access_token, true);
		$criteria->compare('is_online', $this->is_online);
		$criteria->compare('device_id', $this->device_id, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}