<?php

/**
 * This is the model base class for the table "tbl_categories".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Categories".
 *
 * Columns in table "tbl_categories" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $cat_id
 * @property string $cat_name
 * @property integer $status
 * @property string $description
 * @property integer $created_at
 * @property integer $updated_at
 *
 */
abstract class BaseCategories extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_categories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Categories|Categories', $n);
	}

	public static function representingColumn() {
		return 'cat_name';
	}

	public function rules() {
		return array(
			array('status, created_at, updated_at', 'numerical', 'integerOnly'=>true),
			array('cat_name', 'length', 'max'=>255),
			array('description', 'safe'),
			array('cat_name, status, description, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('cat_id, cat_name, status, description, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'cat_id' => Yii::t('app', 'Cat'),
			'cat_name' => Yii::t('app', 'Cat Name'),
			'status' => Yii::t('app', 'Status'),
			'description' => Yii::t('app', 'Description'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('cat_id', $this->cat_id);
		$criteria->compare('cat_name', $this->cat_name, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}