<?php

/**
 * This is the model base class for the table "tbl_images".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Images".
 *
 * Columns in table "tbl_images" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $img_id
 * @property string $img_url
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $post_id
 * @property integer $created_by
 * @property integer $comment_id
 * @property integer $album_id
 * @property integer $image_like_count
 *
 */
abstract class BaseImages extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_images';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Images|Images', $n);
	}

	public static function representingColumn() {
		return 'img_url';
	}

	public function rules() {
		return array(
			array('status, created_at, updated_at, post_id, created_by, comment_id, album_id, image_like_count', 'numerical', 'integerOnly'=>true),
			array('img_url', 'length', 'max'=>255),
			array('img_url, status, created_at, updated_at, post_id, created_by, comment_id, album_id, image_like_count', 'default', 'setOnEmpty' => true, 'value' => null),
			array('img_id, img_url, status, created_at, updated_at, post_id, created_by, comment_id, album_id, image_like_count', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
                    'posts'=>array(self::BELONGS_TO, 'Posts', 'post_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'img_id' => Yii::t('app', 'Img'),
			'img_url' => Yii::t('app', 'Img Url'),
			'status' => Yii::t('app', 'Status'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'post_id' => Yii::t('app', 'Post'),
			'created_by' => Yii::t('app', 'Created By'),
			'comment_id' => Yii::t('app', 'Comment'),
			'album_id' => Yii::t('app', 'Album'),
			'image_like_count' => Yii::t('app', 'Image Like Count'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('img_id', $this->img_id);
		$criteria->compare('img_url', $this->img_url, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('comment_id', $this->comment_id);
		$criteria->compare('album_id', $this->album_id);
		$criteria->compare('image_like_count', $this->image_like_count);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}