<?php

/**
 * This is the model base class for the table "tbl_user_post_relationship".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserPostRelationship".
 *
 * Columns in table "tbl_user_post_relationship" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $post_id
 * @property string $type
 * @property integer $created_at
 * @property integer $updated_at
 *
 */
abstract class BaseUserPostRelationship extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_user_post_relationship';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserPostRelationship|UserPostRelationships', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('user_id, post_id, created_at, updated_at', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>255),
			array('user_id, post_id, type, created_at, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, post_id, type, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'post_id' => Yii::t('app', 'Post'),
			'type' => Yii::t('app', 'Type'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}