<?php

/**
 * This is the model base class for the table "tbl_notifications".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Notifications".
 *
 * Columns in table "tbl_notifications" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $action
 * @property integer $created_at
 * @property string $type
 * @property integer $is_read
 * @property string $content
 * @property integer $recipient_id
 * @property string $url
 *
 */
abstract class BaseNotifications extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_notifications';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Notifications|Notifications', $n);
	}

	public static function representingColumn() {
		return 'action';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id, user_id, created_at, is_read, recipient_id', 'numerical', 'integerOnly'=>true),
			array('action, type, url', 'length', 'max'=>255),
			array('content', 'safe'),
			array('user_id, action, created_at, type, is_read, content, recipient_id, url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, action, created_at, type, is_read, content, recipient_id, url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'action' => Yii::t('app', 'Action'),
			'created_at' => Yii::t('app', 'Created At'),
			'type' => Yii::t('app', 'Type'),
			'is_read' => Yii::t('app', 'Is Read'),
			'content' => Yii::t('app', 'Content'),
			'recipient_id' => Yii::t('app', 'Recipient'),
			'url' => Yii::t('app', 'Url'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('action', $this->action, true);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('is_read', $this->is_read);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('recipient_id', $this->recipient_id);
		$criteria->compare('url', $this->url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}