<?php

/**
 * This is the model base class for the table "tbl_like".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Like".
 *
 * Columns in table "tbl_like" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $from
 * @property integer $post_id
 * @property integer $image_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $status
 * @property integer $to
 *
 */
abstract class BaseLike extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_like';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Like|Likes', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('from, post_id, image_id, created_at, updated_at, status, to', 'numerical', 'integerOnly'=>true),
			array('from, post_id, image_id, created_at, updated_at, status, to', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, from, post_id, image_id, created_at, updated_at, status, to', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'from' => Yii::t('app', 'From'),
			'post_id' => Yii::t('app', 'Post'),
			'image_id' => Yii::t('app', 'Image'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => Yii::t('app', 'Status'),
			'to' => Yii::t('app', 'To'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('from', $this->from);
		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('image_id', $this->image_id);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('updated_at', $this->updated_at);
		$criteria->compare('status', $this->status);
		$criteria->compare('to', $this->to);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}